name: Wikipedia Checker

on:
  workflow_dispatch:

  schedule:
    - cron: "0 23 14,28 * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Google credentials
        run: |
          printf '%s' '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
          printf '%s' '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Run Wikipedia Checker
        env:
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: |
          python wikipedia_checker.py